<?php

// $Id$

require_once drupal_get_path('module', 'livechat') . '/Livechat.php';

/*
 * @file
 * Drupal Module: livechat
 */

function livechat_menu()
{
	$items['admin/settings/livechat'] = array(
		'title' => 'LiveChat',
		'description' => 'Integrate LiveChat software with your website.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('livechat_admin_settings_form'),
		'access arguments' => array('administer ting settings'),
		'file' => 'livechat.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function livechat_init()
{
	if (!path_is_admin(current_path()))
		Livechat::get_instance()->install_codes();
		drupal_add_js(drupal_get_path('module', 'livechat') . '/js/mobile_detect.js', 'file');
}
